// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CourseStatus.
const (
	Archived  CourseStatus = "archived"
	Draft     CourseStatus = "draft"
	Published CourseStatus = "published"
)

// Valid indicates whether the value is a known member of the CourseStatus enum.
func (e CourseStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for LessonDataLessonType.
const (
	Mixed LessonDataLessonType = "mixed"
	Quiz  LessonDataLessonType = "quiz"
	Text  LessonDataLessonType = "text"
	Video LessonDataLessonType = "video"
)

// Valid indicates whether the value is a known member of the LessonDataLessonType enum.
func (e LessonDataLessonType) Valid() bool {
	switch e {
	case Mixed:
		return true
	case Quiz:
		return true
	case Text:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleStudent UserRole = "student"
	UserRoleTeacher UserRole = "teacher"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleStudent:
		return true
	case UserRoleTeacher:
		return true
	default:
		return false
	}
}

// Defines values for GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus.
const (
	ATRISK  GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus = "AT_RISK"
	ONTRACK GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus = "ON_TRACK"
)

// Valid indicates whether the value is a known member of the GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus enum.
func (e GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus) Valid() bool {
	switch e {
	case ATRISK:
		return true
	case ONTRACK:
		return true
	default:
		return false
	}
}

// Defines values for PostAuthRegisterJSONBodyRole.
const (
	PostAuthRegisterJSONBodyRoleStudent PostAuthRegisterJSONBodyRole = "student"
	PostAuthRegisterJSONBodyRoleTeacher PostAuthRegisterJSONBodyRole = "teacher"
)

// Valid indicates whether the value is a known member of the PostAuthRegisterJSONBodyRole enum.
func (e PostAuthRegisterJSONBodyRole) Valid() bool {
	switch e {
	case PostAuthRegisterJSONBodyRoleStudent:
		return true
	case PostAuthRegisterJSONBodyRoleTeacher:
		return true
	default:
		return false
	}
}

// Defines values for GetCatalogCoursesParamsSortBy.
const (
	CreatedAt GetCatalogCoursesParamsSortBy = "created_at"
	Price     GetCatalogCoursesParamsSortBy = "price"
	Subject   GetCatalogCoursesParamsSortBy = "subject"
	Title     GetCatalogCoursesParamsSortBy = "title"
)

// Valid indicates whether the value is a known member of the GetCatalogCoursesParamsSortBy enum.
func (e GetCatalogCoursesParamsSortBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Price:
		return true
	case Subject:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// Defines values for GetCatalogCoursesParamsSortOrder.
const (
	Asc  GetCatalogCoursesParamsSortOrder = "asc"
	Desc GetCatalogCoursesParamsSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the GetCatalogCoursesParamsSortOrder enum.
func (e GetCatalogCoursesParamsSortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for PostPurchaseWebhookJSONBodyStatus.
const (
	REFUNDED PostPurchaseWebhookJSONBodyStatus = "REFUNDED"
	SUCCESS  PostPurchaseWebhookJSONBodyStatus = "SUCCESS"
)

// Valid indicates whether the value is a known member of the PostPurchaseWebhookJSONBodyStatus enum.
func (e PostPurchaseWebhookJSONBodyStatus) Valid() bool {
	switch e {
	case REFUNDED:
		return true
	case SUCCESS:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

// Course defines model for Course.
type Course struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Currency    *string             `json:"currency,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Price       *float32            `json:"price,omitempty"`
	Status      *CourseStatus       `json:"status,omitempty"`

	// Subject Subject area, e.g. "english", "programming", "physics"
	Subject   *string             `json:"subject,omitempty"`
	TeacherId *openapi_types.UUID `json:"teacher_id,omitempty"`
	Title     *string             `json:"title,omitempty"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
}

// CourseStatus defines model for Course.Status.
type CourseStatus string

// LessonData defines model for LessonData.
type LessonData struct {
	// ContentUrl Primary playable media URL for the lesson ("" when the lesson has no media).
	ContentUrl *string `json:"content_url,omitempty"`
	CourseId   *string `json:"course_id,omitempty"`

	// DurationSeconds Length of the primary media in seconds (0 when unknown).
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// LastProgressSeconds The learner's last saved playback offset (0 if never started).
	LastProgressSeconds *int                  `json:"last_progress_seconds,omitempty"`
	LessonId            *string               `json:"lesson_id,omitempty"`
	LessonType          *LessonDataLessonType `json:"lesson_type,omitempty"`
	Materials           *[]Material           `json:"materials,omitempty"`

	// PercentComplete The learner's saved completion percentage (0–100).
	PercentComplete *float32 `json:"percent_complete,omitempty"`
	Position        *int     `json:"position,omitempty"`
	Title           *string  `json:"title,omitempty"`
}

// LessonDataLessonType defines model for LessonData.LessonType.
type LessonDataLessonType string

// Material defines model for Material.
type Material struct {
	Title *string `json:"title,omitempty"`
	Type  *string `json:"type,omitempty"`
	Url   *string `json:"url,omitempty"`
}

// Progress defines model for Progress.
type Progress struct {
	Completed       *bool      `json:"completed,omitempty"`
	LessonId        *string    `json:"lesson_id,omitempty"`
	PercentComplete *float32   `json:"percent_complete,omitempty"`
	ProgressSeconds *int       `json:"progress_seconds,omitempty"`
	UpdatedAt       *time.Time `json:"updated_at,omitempty"`
}

// User defines model for User.
type User struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	FullName *string              `json:"full_name,omitempty"`
	Id       *openapi_types.UUID  `json:"id,omitempty"`
	Role     *UserRole            `json:"role,omitempty"`
}

// UserRole defines model for User.Role.
type UserRole string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetAnalyticsTeacherDashboardParams defines parameters for GetAnalyticsTeacherDashboard.
type GetAnalyticsTeacherDashboardParams struct {
	CourseId string `form:"course_id" json:"course_id"`
}

// GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus defines parameters for GetAnalyticsTeacherDashboard.
type GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus string

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PostAuthRegisterJSONBody defines parameters for PostAuthRegister.
type PostAuthRegisterJSONBody struct {
	// AnonymousId Links pre-auth anonymous activity to this account, if any.
	AnonymousId *openapi_types.UUID          `json:"anonymous_id,omitempty"`
	Email       openapi_types.Email          `json:"email"`
	FullName    string                       `json:"full_name"`
	Password    string                       `json:"password"`
	Role        PostAuthRegisterJSONBodyRole `json:"role"`
}

// PostAuthRegisterJSONBodyRole defines parameters for PostAuthRegister.
type PostAuthRegisterJSONBodyRole string

// GetCatalogCoursesParams defines parameters for GetCatalogCourses.
type GetCatalogCoursesParams struct {
	// Search Course title/description keyword search
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Subject Partial, case-insensitive match against the course subject (e.g. "program" matches "Programming")
	Subject *string `form:"subject,omitempty" json:"subject,omitempty"`

	// MinPrice Lower bound (inclusive) for course price
	MinPrice *float32 `form:"min_price,omitempty" json:"min_price,omitempty"`

	// MaxPrice Upper bound (inclusive) for course price
	MaxPrice  *float32                          `form:"max_price,omitempty" json:"max_price,omitempty"`
	SortBy    *GetCatalogCoursesParamsSortBy    `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	SortOrder *GetCatalogCoursesParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`
	Page      *int                              `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *int                              `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetCatalogCoursesParamsSortBy defines parameters for GetCatalogCourses.
type GetCatalogCoursesParamsSortBy string

// GetCatalogCoursesParamsSortOrder defines parameters for GetCatalogCourses.
type GetCatalogCoursesParamsSortOrder string

// PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody defines parameters for PostPlayerCoursesCourseIdLessonsLessonIdProgress.
type PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody struct {
	// Completed Marks the lesson finished (forces percent_complete to 100).
	Completed *bool `json:"completed,omitempty"`

	// ProgressSeconds Current playback offset, in seconds.
	ProgressSeconds int `json:"progress_seconds"`
}

// PostPurchaseCheckoutJSONBody defines parameters for PostPurchaseCheckout.
type PostPurchaseCheckoutJSONBody struct {
	CourseId string `json:"course_id"`
}

// PostPurchaseRefundJSONBody defines parameters for PostPurchaseRefund.
type PostPurchaseRefundJSONBody struct {
	CourseId string `json:"course_id"`
}

// PostPurchaseWebhookJSONBody defines parameters for PostPurchaseWebhook.
type PostPurchaseWebhookJSONBody struct {
	CourseId      *string                            `json:"course_id,omitempty"`
	Status        *PostPurchaseWebhookJSONBodyStatus `json:"status,omitempty"`
	TransactionId *string                            `json:"transaction_id,omitempty"`
	UserId        *string                            `json:"user_id,omitempty"`
}

// PostPurchaseWebhookJSONBodyStatus defines parameters for PostPurchaseWebhook.
type PostPurchaseWebhookJSONBodyStatus string

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody PostAuthRegisterJSONBody

// PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONRequestBody defines body for PostPlayerCoursesCourseIdLessonsLessonIdProgress for application/json ContentType.
type PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONRequestBody PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody

// PostPurchaseCheckoutJSONRequestBody defines body for PostPurchaseCheckout for application/json ContentType.
type PostPurchaseCheckoutJSONRequestBody PostPurchaseCheckoutJSONBody

// PostPurchaseRefundJSONRequestBody defines body for PostPurchaseRefund for application/json ContentType.
type PostPurchaseRefundJSONRequestBody PostPurchaseRefundJSONBody

// PostPurchaseWebhookJSONRequestBody defines body for PostPurchaseWebhook for application/json ContentType.
type PostPurchaseWebhookJSONRequestBody PostPurchaseWebhookJSONBody
