//go:build go1.22

// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Personal student progress across enrolled courses
	// (GET /analytics/student/me)
	GetAnalyticsStudentMe(w http.ResponseWriter, r *http.Request)
	// Aggregated teacher view to detect struggling students
	// (GET /analytics/teacher/dashboard)
	GetAnalyticsTeacherDashboard(w http.ResponseWriter, r *http.Request, params GetAnalyticsTeacherDashboardParams)
	// Login via email/password
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Get the currently authenticated user's profile
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Create a new student or teacher account
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Browsable catalog of courses with simple filtering
	// (GET /catalog/courses)
	GetCatalogCourses(w http.ResponseWriter, r *http.Request, params GetCatalogCoursesParams)
	// Leave a review for a course
	// (POST /catalog/courses/{course_id}/comments)
	PostCatalogCoursesCourseIdComments(w http.ResponseWriter, r *http.Request, courseId openapi_types.UUID)
	// List all lessons for a course
	// (GET /catalog/courses/{course_id}/lessons)
	GetCatalogCoursesCourseIdLessons(w http.ResponseWriter, r *http.Request, courseId openapi_types.UUID)
	// A course's aggregate rating
	// (GET /catalog/courses/{course_id}/rating)
	GetCatalogCoursesCourseIdRating(w http.ResponseWriter, r *http.Request, courseId openapi_types.UUID)
	// The calling student's conversation with the course's teacher
	// (GET /courses/{course_id}/messages)
	GetCoursesCourseIdMessages(w http.ResponseWriter, r *http.Request, courseId string)
	// Student sends a message to the course's teacher
	// (POST /courses/{course_id}/messages)
	PostCoursesCourseIdMessages(w http.ResponseWriter, r *http.Request, courseId string)
	// Database connectivity check
	// (GET /health/db)
	GetHealthDb(w http.ResponseWriter, r *http.Request)
	// Liveness check
	// (GET /hello)
	GetHello(w http.ResponseWriter, r *http.Request)
	// Request to play a lesson (Enforces Access/Entitlement)
	// (GET /player/courses/{course_id}/lessons/{lesson_id})
	GetPlayerCoursesCourseIdLessonsLessonId(w http.ResponseWriter, r *http.Request, courseId string, lessonId string)
	// Fetch the learner's saved resume point for a lesson
	// (GET /player/courses/{course_id}/lessons/{lesson_id}/progress)
	GetPlayerCoursesCourseIdLessonsLessonIdProgress(w http.ResponseWriter, r *http.Request, courseId string, lessonId string)
	// Saves current play progress to DB
	// (POST /player/courses/{course_id}/lessons/{lesson_id}/progress)
	PostPlayerCoursesCourseIdLessonsLessonIdProgress(w http.ResponseWriter, r *http.Request, courseId string, lessonId string)
	// Initiate mock sandbox purchase for a course
	// (POST /purchase/checkout)
	PostPurchaseCheckout(w http.ResponseWriter, r *http.Request)
	// List the caller's payment history (purchases and refunds), newest first
	// (GET /purchase/history)
	GetPurchaseHistory(w http.ResponseWriter, r *http.Request)
	// Return a purchased course and refund the full amount to the buyer's virtual wallet
	// (POST /purchase/refund)
	PostPurchaseRefund(w http.ResponseWriter, r *http.Request)
	// Idempotent webhook entrypoint (Mocks payment success or refund/revocation)
	// (POST /purchase/webhook)
	PostPurchaseWebhook(w http.ResponseWriter, r *http.Request)
	// Create a new draft course owned by the caller
	// (POST /teacher/courses)
	PostTeacherCourses(w http.ResponseWriter, r *http.Request)
	// Delete a draft course (published/archived courses must be archived instead)
	// (DELETE /teacher/courses/{course_id})
	DeleteTeacherCoursesCourseId(w http.ResponseWriter, r *http.Request, courseId string)
	// Update an owned course's fields and status
	// (PATCH /teacher/courses/{course_id})
	PatchTeacherCoursesCourseId(w http.ResponseWriter, r *http.Request, courseId string)
	// Append a new lesson to an owned course
	// (POST /teacher/courses/{course_id}/lessons)
	PostTeacherCoursesCourseIdLessons(w http.ResponseWriter, r *http.Request, courseId string)
	// Reorder an owned course's lessons
	// (PUT /teacher/courses/{course_id}/lessons/order)
	PutTeacherCoursesCourseIdLessonsOrder(w http.ResponseWriter, r *http.Request, courseId string)
	// Delete a lesson (and its media/materials)
	// (DELETE /teacher/courses/{course_id}/lessons/{lesson_id})
	DeleteTeacherCoursesCourseIdLessonsLessonId(w http.ResponseWriter, r *http.Request, courseId string, lessonId string)
	// Update an owned lesson's title/type
	// (PATCH /teacher/courses/{course_id}/lessons/{lesson_id})
	PatchTeacherCoursesCourseIdLessonsLessonId(w http.ResponseWriter, r *http.Request, courseId string, lessonId string)
	// Attach a downloadable material to a lesson
	// (POST /teacher/courses/{course_id}/lessons/{lesson_id}/materials)
	PostTeacherCoursesCourseIdLessonsLessonIdMaterials(w http.ResponseWriter, r *http.Request, courseId string, lessonId string)
	// Remove a single material from a lesson
	// (DELETE /teacher/courses/{course_id}/lessons/{lesson_id}/materials/{material_id})
	DeleteTeacherCoursesCourseIdLessonsLessonIdMaterialsMaterialId(w http.ResponseWriter, r *http.Request, courseId string, lessonId string, materialId string)
	// Remove a lesson's media asset, if any
	// (DELETE /teacher/courses/{course_id}/lessons/{lesson_id}/media)
	DeleteTeacherCoursesCourseIdLessonsLessonIdMedia(w http.ResponseWriter, r *http.Request, courseId string, lessonId string)
	// Replace a lesson's playable media asset
	// (PUT /teacher/courses/{course_id}/lessons/{lesson_id}/media)
	PutTeacherCoursesCourseIdLessonsLessonIdMedia(w http.ResponseWriter, r *http.Request, courseId string, lessonId string)
	// The owning teacher's inbox of student conversations
	// (GET /teacher/courses/{course_id}/threads)
	GetTeacherCoursesCourseIdThreads(w http.ResponseWriter, r *http.Request, courseId string)
	// The owning teacher reads one student's thread
	// (GET /teacher/courses/{course_id}/threads/{student_id}/messages)
	GetTeacherCoursesCourseIdThreadsStudentIdMessages(w http.ResponseWriter, r *http.Request, courseId string, studentId string)
	// The owning teacher replies in a student's thread
	// (POST /teacher/courses/{course_id}/threads/{student_id}/messages)
	PostTeacherCoursesCourseIdThreadsStudentIdMessages(w http.ResponseWriter, r *http.Request, courseId string, studentId string)
	// Get a teacher's public profile
	// (GET /teachers/{teacher_id})
	GetTeachersTeacherId(w http.ResponseWriter, r *http.Request, teacherId openapi_types.UUID)
	// Upload a profile picture
	// (POST /users/me/avatar)
	PostUsersMeAvatar(w http.ResponseWriter, r *http.Request)
	// Get courses for the authenticated user
	// (GET /users/me/courses)
	GetUsersMeCourses(w http.ResponseWriter, r *http.Request)
	// Change the authenticated user's email address
	// (PATCH /users/me/email)
	PatchUsersMeEmail(w http.ResponseWriter, r *http.Request)
	// Change the authenticated user's display name
	// (PATCH /users/me/name)
	PatchUsersMeName(w http.ResponseWriter, r *http.Request)
	// Change the authenticated user's password
	// (PATCH /users/me/password)
	PatchUsersMePassword(w http.ResponseWriter, r *http.Request)
	// Aggregated progress across the caller's enrolled courses
	// (GET /users/me/results)
	GetUsersMeResults(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAnalyticsStudentMe operation middleware
func (siw *ServerInterfaceWrapper) GetAnalyticsStudentMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalyticsStudentMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAnalyticsTeacherDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetAnalyticsTeacherDashboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnalyticsTeacherDashboardParams

	// ------------- Required query parameter "course_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "course_id", r.URL.Query(), &params.CourseId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "course_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalyticsTeacherDashboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCatalogCourses operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogCourses(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCatalogCoursesParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "subject" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subject", r.URL.Query(), &params.Subject, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "subject"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_price" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_price", r.URL.Query(), &params.MinPrice, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_price"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_price", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "max_price" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_price", r.URL.Query(), &params.MaxPrice, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_price"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_price", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "difficulty" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "difficulty", r.URL.Query(), &params.Difficulty, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "difficulty"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "difficulty", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_by", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort_by"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort_order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_order", r.URL.Query(), &params.SortOrder, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort_order"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_order", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCatalogCourses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCatalogCoursesCourseIdComments operation middleware
func (siw *ServerInterfaceWrapper) PostCatalogCoursesCourseIdComments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCatalogCoursesCourseIdComments(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCatalogCoursesCourseIdLessons operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogCoursesCourseIdLessons(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCatalogCoursesCourseIdLessons(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCatalogCoursesCourseIdRating operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogCoursesCourseIdRating(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCatalogCoursesCourseIdRating(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCoursesCourseIdMessages operation middleware
func (siw *ServerInterfaceWrapper) GetCoursesCourseIdMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCoursesCourseIdMessages(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCoursesCourseIdMessages operation middleware
func (siw *ServerInterfaceWrapper) PostCoursesCourseIdMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCoursesCourseIdMessages(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthDb operation middleware
func (siw *ServerInterfaceWrapper) GetHealthDb(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthDb(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHello operation middleware
func (siw *ServerInterfaceWrapper) GetHello(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHello(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlayerCoursesCourseIdLessonsLessonId operation middleware
func (siw *ServerInterfaceWrapper) GetPlayerCoursesCourseIdLessonsLessonId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlayerCoursesCourseIdLessonsLessonId(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlayerCoursesCourseIdLessonsLessonIdProgress operation middleware
func (siw *ServerInterfaceWrapper) GetPlayerCoursesCourseIdLessonsLessonIdProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlayerCoursesCourseIdLessonsLessonIdProgress(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPlayerCoursesCourseIdLessonsLessonIdProgress operation middleware
func (siw *ServerInterfaceWrapper) PostPlayerCoursesCourseIdLessonsLessonIdProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPlayerCoursesCourseIdLessonsLessonIdProgress(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPurchaseCheckout operation middleware
func (siw *ServerInterfaceWrapper) PostPurchaseCheckout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPurchaseCheckout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPurchaseHistory operation middleware
func (siw *ServerInterfaceWrapper) GetPurchaseHistory(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPurchaseHistory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPurchaseRefund operation middleware
func (siw *ServerInterfaceWrapper) PostPurchaseRefund(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPurchaseRefund(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPurchaseWebhook operation middleware
func (siw *ServerInterfaceWrapper) PostPurchaseWebhook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPurchaseWebhook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeacherCourses operation middleware
func (siw *ServerInterfaceWrapper) PostTeacherCourses(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeacherCourses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTeacherCoursesCourseId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeacherCoursesCourseId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeacherCoursesCourseId(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchTeacherCoursesCourseId operation middleware
func (siw *ServerInterfaceWrapper) PatchTeacherCoursesCourseId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchTeacherCoursesCourseId(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeacherCoursesCourseIdLessons operation middleware
func (siw *ServerInterfaceWrapper) PostTeacherCoursesCourseIdLessons(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeacherCoursesCourseIdLessons(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTeacherCoursesCourseIdLessonsOrder operation middleware
func (siw *ServerInterfaceWrapper) PutTeacherCoursesCourseIdLessonsOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTeacherCoursesCourseIdLessonsOrder(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTeacherCoursesCourseIdLessonsLessonId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeacherCoursesCourseIdLessonsLessonId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeacherCoursesCourseIdLessonsLessonId(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchTeacherCoursesCourseIdLessonsLessonId operation middleware
func (siw *ServerInterfaceWrapper) PatchTeacherCoursesCourseIdLessonsLessonId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchTeacherCoursesCourseIdLessonsLessonId(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeacherCoursesCourseIdLessonsLessonIdMaterials operation middleware
func (siw *ServerInterfaceWrapper) PostTeacherCoursesCourseIdLessonsLessonIdMaterials(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeacherCoursesCourseIdLessonsLessonIdMaterials(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTeacherCoursesCourseIdLessonsLessonIdMaterialsMaterialId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeacherCoursesCourseIdLessonsLessonIdMaterialsMaterialId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	// ------------- Path parameter "material_id" -------------
	var materialId string

	err = runtime.BindStyledParameterWithOptions("simple", "material_id", r.PathValue("material_id"), &materialId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "material_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeacherCoursesCourseIdLessonsLessonIdMaterialsMaterialId(w, r, courseId, lessonId, materialId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTeacherCoursesCourseIdLessonsLessonIdMedia operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeacherCoursesCourseIdLessonsLessonIdMedia(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeacherCoursesCourseIdLessonsLessonIdMedia(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTeacherCoursesCourseIdLessonsLessonIdMedia operation middleware
func (siw *ServerInterfaceWrapper) PutTeacherCoursesCourseIdLessonsLessonIdMedia(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "lesson_id" -------------
	var lessonId string

	err = runtime.BindStyledParameterWithOptions("simple", "lesson_id", r.PathValue("lesson_id"), &lessonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lesson_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTeacherCoursesCourseIdLessonsLessonIdMedia(w, r, courseId, lessonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeacherCoursesCourseIdThreads operation middleware
func (siw *ServerInterfaceWrapper) GetTeacherCoursesCourseIdThreads(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeacherCoursesCourseIdThreads(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeacherCoursesCourseIdThreadsStudentIdMessages operation middleware
func (siw *ServerInterfaceWrapper) GetTeacherCoursesCourseIdThreadsStudentIdMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "student_id" -------------
	var studentId string

	err = runtime.BindStyledParameterWithOptions("simple", "student_id", r.PathValue("student_id"), &studentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "student_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeacherCoursesCourseIdThreadsStudentIdMessages(w, r, courseId, studentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeacherCoursesCourseIdThreadsStudentIdMessages operation middleware
func (siw *ServerInterfaceWrapper) PostTeacherCoursesCourseIdThreadsStudentIdMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "course_id" -------------
	var courseId string

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", r.PathValue("course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	// ------------- Path parameter "student_id" -------------
	var studentId string

	err = runtime.BindStyledParameterWithOptions("simple", "student_id", r.PathValue("student_id"), &studentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "student_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeacherCoursesCourseIdThreadsStudentIdMessages(w, r, courseId, studentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeachersTeacherId operation middleware
func (siw *ServerInterfaceWrapper) GetTeachersTeacherId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "teacher_id" -------------
	var teacherId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "teacher_id", r.PathValue("teacher_id"), &teacherId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "teacher_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeachersTeacherId(w, r, teacherId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersMeAvatar operation middleware
func (siw *ServerInterfaceWrapper) PostUsersMeAvatar(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersMeAvatar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersMeCourses operation middleware
func (siw *ServerInterfaceWrapper) GetUsersMeCourses(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersMeCourses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchUsersMeEmail operation middleware
func (siw *ServerInterfaceWrapper) PatchUsersMeEmail(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchUsersMeEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchUsersMeName operation middleware
func (siw *ServerInterfaceWrapper) PatchUsersMeName(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchUsersMeName(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchUsersMePassword operation middleware
func (siw *ServerInterfaceWrapper) PatchUsersMePassword(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchUsersMePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersMeResults operation middleware
func (siw *ServerInterfaceWrapper) GetUsersMeResults(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersMeResults(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/analytics/student/me", wrapper.GetAnalyticsStudentMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/analytics/teacher/dashboard", wrapper.GetAnalyticsTeacherDashboard)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/catalog/courses", wrapper.GetCatalogCourses)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/catalog/courses/{course_id}/comments", wrapper.PostCatalogCoursesCourseIdComments)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/catalog/courses/{course_id}/lessons", wrapper.GetCatalogCoursesCourseIdLessons)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/catalog/courses/{course_id}/rating", wrapper.GetCatalogCoursesCourseIdRating)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/courses/{course_id}/messages", wrapper.GetCoursesCourseIdMessages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/courses/{course_id}/messages", wrapper.PostCoursesCourseIdMessages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/db", wrapper.GetHealthDb)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/hello", wrapper.GetHello)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/player/courses/{course_id}/lessons/{lesson_id}", wrapper.GetPlayerCoursesCourseIdLessonsLessonId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/player/courses/{course_id}/lessons/{lesson_id}/progress", wrapper.GetPlayerCoursesCourseIdLessonsLessonIdProgress)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/player/courses/{course_id}/lessons/{lesson_id}/progress", wrapper.PostPlayerCoursesCourseIdLessonsLessonIdProgress)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/purchase/checkout", wrapper.PostPurchaseCheckout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/purchase/history", wrapper.GetPurchaseHistory)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/purchase/refund", wrapper.PostPurchaseRefund)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/purchase/webhook", wrapper.PostPurchaseWebhook)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/teacher/courses", wrapper.PostTeacherCourses)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/teacher/courses/{course_id}", wrapper.DeleteTeacherCoursesCourseId)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/teacher/courses/{course_id}", wrapper.PatchTeacherCoursesCourseId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/teacher/courses/{course_id}/lessons", wrapper.PostTeacherCoursesCourseIdLessons)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/teacher/courses/{course_id}/lessons/order", wrapper.PutTeacherCoursesCourseIdLessonsOrder)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/teacher/courses/{course_id}/lessons/{lesson_id}", wrapper.DeleteTeacherCoursesCourseIdLessonsLessonId)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/teacher/courses/{course_id}/lessons/{lesson_id}", wrapper.PatchTeacherCoursesCourseIdLessonsLessonId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/teacher/courses/{course_id}/lessons/{lesson_id}/materials", wrapper.PostTeacherCoursesCourseIdLessonsLessonIdMaterials)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/teacher/courses/{course_id}/lessons/{lesson_id}/materials/{material_id}", wrapper.DeleteTeacherCoursesCourseIdLessonsLessonIdMaterialsMaterialId)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/teacher/courses/{course_id}/lessons/{lesson_id}/media", wrapper.DeleteTeacherCoursesCourseIdLessonsLessonIdMedia)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/teacher/courses/{course_id}/lessons/{lesson_id}/media", wrapper.PutTeacherCoursesCourseIdLessonsLessonIdMedia)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/teacher/courses/{course_id}/threads", wrapper.GetTeacherCoursesCourseIdThreads)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/teacher/courses/{course_id}/threads/{student_id}/messages", wrapper.GetTeacherCoursesCourseIdThreadsStudentIdMessages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/teacher/courses/{course_id}/threads/{student_id}/messages", wrapper.PostTeacherCoursesCourseIdThreadsStudentIdMessages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/teachers/{teacher_id}", wrapper.GetTeachersTeacherId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users/me/avatar", wrapper.PostUsersMeAvatar)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/me/courses", wrapper.GetUsersMeCourses)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/users/me/email", wrapper.PatchUsersMeEmail)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/users/me/name", wrapper.PatchUsersMeName)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/users/me/password", wrapper.PatchUsersMePassword)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/me/results", wrapper.GetUsersMeResults)

	return m
}
