// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CourseStatus.
const (
	Archived  CourseStatus = "archived"
	Draft     CourseStatus = "draft"
	Published CourseStatus = "published"
)

// Valid indicates whether the value is a known member of the CourseStatus enum.
func (e CourseStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus.
const (
	ATRISK  GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus = "AT_RISK"
	ONTRACK GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus = "ON_TRACK"
)

// Valid indicates whether the value is a known member of the GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus enum.
func (e GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus) Valid() bool {
	switch e {
	case ATRISK:
		return true
	case ONTRACK:
		return true
	default:
		return false
	}
}

// Defines values for GetCatalogCoursesParamsSortBy.
const (
	CreatedAt GetCatalogCoursesParamsSortBy = "created_at"
	Price     GetCatalogCoursesParamsSortBy = "price"
	Subject   GetCatalogCoursesParamsSortBy = "subject"
	Title     GetCatalogCoursesParamsSortBy = "title"
)

// Valid indicates whether the value is a known member of the GetCatalogCoursesParamsSortBy enum.
func (e GetCatalogCoursesParamsSortBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Price:
		return true
	case Subject:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// Defines values for GetCatalogCoursesParamsSortOrder.
const (
	Asc  GetCatalogCoursesParamsSortOrder = "asc"
	Desc GetCatalogCoursesParamsSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the GetCatalogCoursesParamsSortOrder enum.
func (e GetCatalogCoursesParamsSortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for PostPurchaseWebhookJSONBodyStatus.
const (
	REFUNDED PostPurchaseWebhookJSONBodyStatus = "REFUNDED"
	SUCCESS  PostPurchaseWebhookJSONBodyStatus = "SUCCESS"
)

// Valid indicates whether the value is a known member of the PostPurchaseWebhookJSONBodyStatus enum.
func (e PostPurchaseWebhookJSONBodyStatus) Valid() bool {
	switch e {
	case REFUNDED:
		return true
	case SUCCESS:
		return true
	default:
		return false
	}
}

// Course defines model for Course.
type Course struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Currency    *string             `json:"currency,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Price       *float32            `json:"price,omitempty"`
	Status      *CourseStatus       `json:"status,omitempty"`

	// Subject Subject area, e.g. "english", "programming", "physics"
	Subject   *string             `json:"subject,omitempty"`
	TeacherId *openapi_types.UUID `json:"teacher_id,omitempty"`
	Title     *string             `json:"title,omitempty"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
}

// CourseStatus defines model for Course.Status.
type CourseStatus string

// LessonData defines model for LessonData.
type LessonData struct {
	ContentUrl          *string `json:"content_url,omitempty"`
	LastProgressSeconds *int    `json:"last_progress_seconds,omitempty"`
	LessonId            *string `json:"lesson_id,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetAnalyticsTeacherDashboardParams defines parameters for GetAnalyticsTeacherDashboard.
type GetAnalyticsTeacherDashboardParams struct {
	CourseId string `form:"course_id" json:"course_id"`
}

// GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus defines parameters for GetAnalyticsTeacherDashboard.
type GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus string

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// GetCatalogCoursesParams defines parameters for GetCatalogCourses.
type GetCatalogCoursesParams struct {
	// Search Course title/description keyword search
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Subject Partial, case-insensitive match against the course subject (e.g. "program" matches "Programming")
	Subject *string `form:"subject,omitempty" json:"subject,omitempty"`

	// MinPrice Lower bound (inclusive) for course price
	MinPrice *float32 `form:"min_price,omitempty" json:"min_price,omitempty"`

	// MaxPrice Upper bound (inclusive) for course price
	MaxPrice  *float32                          `form:"max_price,omitempty" json:"max_price,omitempty"`
	SortBy    *GetCatalogCoursesParamsSortBy    `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	SortOrder *GetCatalogCoursesParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`
	Page      *int                              `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *int                              `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetCatalogCoursesParamsSortBy defines parameters for GetCatalogCourses.
type GetCatalogCoursesParamsSortBy string

// GetCatalogCoursesParamsSortOrder defines parameters for GetCatalogCourses.
type GetCatalogCoursesParamsSortOrder string

// PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody defines parameters for PostPlayerCoursesCourseIdLessonsLessonIdProgress.
type PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody struct {
	Completed       *bool `json:"completed,omitempty"`
	ProgressSeconds *int  `json:"progress_seconds,omitempty"`
}

// PostPurchaseCheckoutJSONBody defines parameters for PostPurchaseCheckout.
type PostPurchaseCheckoutJSONBody struct {
	CourseId string `json:"course_id"`
}

// PostPurchaseWebhookJSONBody defines parameters for PostPurchaseWebhook.
type PostPurchaseWebhookJSONBody struct {
	CourseId      *string                            `json:"course_id,omitempty"`
	Status        *PostPurchaseWebhookJSONBodyStatus `json:"status,omitempty"`
	TransactionId *string                            `json:"transaction_id,omitempty"`
	UserId        *string                            `json:"user_id,omitempty"`
}

// PostPurchaseWebhookJSONBodyStatus defines parameters for PostPurchaseWebhook.
type PostPurchaseWebhookJSONBodyStatus string

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONRequestBody defines body for PostPlayerCoursesCourseIdLessonsLessonIdProgress for application/json ContentType.
type PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONRequestBody PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody

// PostPurchaseCheckoutJSONRequestBody defines body for PostPurchaseCheckout for application/json ContentType.
type PostPurchaseCheckoutJSONRequestBody PostPurchaseCheckoutJSONBody

// PostPurchaseWebhookJSONRequestBody defines body for PostPurchaseWebhook for application/json ContentType.
type PostPurchaseWebhookJSONRequestBody PostPurchaseWebhookJSONBody
