// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CourseStatus.
const (
	CourseStatusArchived  CourseStatus = "archived"
	CourseStatusDraft     CourseStatus = "draft"
	CourseStatusPublished CourseStatus = "published"
)

// Valid indicates whether the value is a known member of the CourseStatus enum.
func (e CourseStatus) Valid() bool {
	switch e {
	case CourseStatusArchived:
		return true
	case CourseStatusDraft:
		return true
	case CourseStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for CourseResultStatus.
const (
	CourseResultStatusATRISK  CourseResultStatus = "AT_RISK"
	CourseResultStatusONTRACK CourseResultStatus = "ON_TRACK"
)

// Valid indicates whether the value is a known member of the CourseResultStatus enum.
func (e CourseResultStatus) Valid() bool {
	switch e {
	case CourseResultStatusATRISK:
		return true
	case CourseResultStatusONTRACK:
		return true
	default:
		return false
	}
}

// Defines values for LessonType.
const (
	LessonTypeMixed LessonType = "mixed"
	LessonTypeQuiz  LessonType = "quiz"
	LessonTypeText  LessonType = "text"
	LessonTypeVideo LessonType = "video"
)

// Valid indicates whether the value is a known member of the LessonType enum.
func (e LessonType) Valid() bool {
	switch e {
	case LessonTypeMixed:
		return true
	case LessonTypeQuiz:
		return true
	case LessonTypeText:
		return true
	case LessonTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for LessonDataLessonType.
const (
	LessonDataLessonTypeMixed LessonDataLessonType = "mixed"
	LessonDataLessonTypeQuiz  LessonDataLessonType = "quiz"
	LessonDataLessonTypeText  LessonDataLessonType = "text"
	LessonDataLessonTypeVideo LessonDataLessonType = "video"
)

// Valid indicates whether the value is a known member of the LessonDataLessonType enum.
func (e LessonDataLessonType) Valid() bool {
	switch e {
	case LessonDataLessonTypeMixed:
		return true
	case LessonDataLessonTypeQuiz:
		return true
	case LessonDataLessonTypeText:
		return true
	case LessonDataLessonTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for LessonDataMediaType.
const (
	LessonDataMediaTypeAudio LessonDataMediaType = "audio"
	LessonDataMediaTypeVideo LessonDataMediaType = "video"
)

// Valid indicates whether the value is a known member of the LessonDataMediaType enum.
func (e LessonDataMediaType) Valid() bool {
	switch e {
	case LessonDataMediaTypeAudio:
		return true
	case LessonDataMediaTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for LessonInputLessonType.
const (
	LessonInputLessonTypeMixed LessonInputLessonType = "mixed"
	LessonInputLessonTypeQuiz  LessonInputLessonType = "quiz"
	LessonInputLessonTypeText  LessonInputLessonType = "text"
	LessonInputLessonTypeVideo LessonInputLessonType = "video"
)

// Valid indicates whether the value is a known member of the LessonInputLessonType enum.
func (e LessonInputLessonType) Valid() bool {
	switch e {
	case LessonInputLessonTypeMixed:
		return true
	case LessonInputLessonTypeQuiz:
		return true
	case LessonInputLessonTypeText:
		return true
	case LessonInputLessonTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for TeacherLessonLessonType.
const (
	TeacherLessonLessonTypeMixed TeacherLessonLessonType = "mixed"
	TeacherLessonLessonTypeQuiz  TeacherLessonLessonType = "quiz"
	TeacherLessonLessonTypeText  TeacherLessonLessonType = "text"
	TeacherLessonLessonTypeVideo TeacherLessonLessonType = "video"
)

// Valid indicates whether the value is a known member of the TeacherLessonLessonType enum.
func (e TeacherLessonLessonType) Valid() bool {
	switch e {
	case TeacherLessonLessonTypeMixed:
		return true
	case TeacherLessonLessonTypeQuiz:
		return true
	case TeacherLessonLessonTypeText:
		return true
	case TeacherLessonLessonTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for TeacherMediaMediaType.
const (
	TeacherMediaMediaTypeAudio TeacherMediaMediaType = "audio"
	TeacherMediaMediaTypeVideo TeacherMediaMediaType = "video"
)

// Valid indicates whether the value is a known member of the TeacherMediaMediaType enum.
func (e TeacherMediaMediaType) Valid() bool {
	switch e {
	case TeacherMediaMediaTypeAudio:
		return true
	case TeacherMediaMediaTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for TeacherProfileRole.
const (
	TeacherProfileRoleTeacher TeacherProfileRole = "teacher"
)

// Valid indicates whether the value is a known member of the TeacherProfileRole enum.
func (e TeacherProfileRole) Valid() bool {
	switch e {
	case TeacherProfileRoleTeacher:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleStudent UserRole = "student"
	UserRoleTeacher UserRole = "teacher"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleStudent:
		return true
	case UserRoleTeacher:
		return true
	default:
		return false
	}
}

// Defines values for GetAnalyticsStudentMe200JSONResponseBodyCoursesStatus.
const (
	GetAnalyticsStudentMe200JSONResponseBodyCoursesStatusATRISK  GetAnalyticsStudentMe200JSONResponseBodyCoursesStatus = "AT_RISK"
	GetAnalyticsStudentMe200JSONResponseBodyCoursesStatusONTRACK GetAnalyticsStudentMe200JSONResponseBodyCoursesStatus = "ON_TRACK"
)

// Valid indicates whether the value is a known member of the GetAnalyticsStudentMe200JSONResponseBodyCoursesStatus enum.
func (e GetAnalyticsStudentMe200JSONResponseBodyCoursesStatus) Valid() bool {
	switch e {
	case GetAnalyticsStudentMe200JSONResponseBodyCoursesStatusATRISK:
		return true
	case GetAnalyticsStudentMe200JSONResponseBodyCoursesStatusONTRACK:
		return true
	default:
		return false
	}
}

// Defines values for GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus.
const (
	ATRISK  GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus = "AT_RISK"
	ONTRACK GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus = "ON_TRACK"
)

// Valid indicates whether the value is a known member of the GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus enum.
func (e GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus) Valid() bool {
	switch e {
	case ATRISK:
		return true
	case ONTRACK:
		return true
	default:
		return false
	}
}

// Defines values for PostAuthRegisterJSONBodyRole.
const (
	Student PostAuthRegisterJSONBodyRole = "student"
	Teacher PostAuthRegisterJSONBodyRole = "teacher"
)

// Valid indicates whether the value is a known member of the PostAuthRegisterJSONBodyRole enum.
func (e PostAuthRegisterJSONBodyRole) Valid() bool {
	switch e {
	case Student:
		return true
	case Teacher:
		return true
	default:
		return false
	}
}

// Defines values for GetCatalogCoursesParamsSortBy.
const (
	CreatedAt GetCatalogCoursesParamsSortBy = "created_at"
	Price     GetCatalogCoursesParamsSortBy = "price"
	Subject   GetCatalogCoursesParamsSortBy = "subject"
	Title     GetCatalogCoursesParamsSortBy = "title"
)

// Valid indicates whether the value is a known member of the GetCatalogCoursesParamsSortBy enum.
func (e GetCatalogCoursesParamsSortBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Price:
		return true
	case Subject:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// Defines values for GetCatalogCoursesParamsSortOrder.
const (
	Asc  GetCatalogCoursesParamsSortOrder = "asc"
	Desc GetCatalogCoursesParamsSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the GetCatalogCoursesParamsSortOrder enum.
func (e GetCatalogCoursesParamsSortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for PostPurchaseWebhookJSONBodyStatus.
const (
	REFUNDED PostPurchaseWebhookJSONBodyStatus = "REFUNDED"
	SUCCESS  PostPurchaseWebhookJSONBodyStatus = "SUCCESS"
)

// Valid indicates whether the value is a known member of the PostPurchaseWebhookJSONBodyStatus enum.
func (e PostPurchaseWebhookJSONBodyStatus) Valid() bool {
	switch e {
	case REFUNDED:
		return true
	case SUCCESS:
		return true
	default:
		return false
	}
}

// Defines values for PatchTeacherCoursesCourseIdJSONBodyStatus.
const (
	PatchTeacherCoursesCourseIdJSONBodyStatusArchived  PatchTeacherCoursesCourseIdJSONBodyStatus = "archived"
	PatchTeacherCoursesCourseIdJSONBodyStatusDraft     PatchTeacherCoursesCourseIdJSONBodyStatus = "draft"
	PatchTeacherCoursesCourseIdJSONBodyStatusPublished PatchTeacherCoursesCourseIdJSONBodyStatus = "published"
)

// Valid indicates whether the value is a known member of the PatchTeacherCoursesCourseIdJSONBodyStatus enum.
func (e PatchTeacherCoursesCourseIdJSONBodyStatus) Valid() bool {
	switch e {
	case PatchTeacherCoursesCourseIdJSONBodyStatusArchived:
		return true
	case PatchTeacherCoursesCourseIdJSONBodyStatusDraft:
		return true
	case PatchTeacherCoursesCourseIdJSONBodyStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBodyMediaType.
const (
	Audio PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBodyMediaType = "audio"
	Video PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBodyMediaType = "video"
)

// Valid indicates whether the value is a known member of the PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBodyMediaType enum.
func (e PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBodyMediaType) Valid() bool {
	switch e {
	case Audio:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

// Course defines model for Course.
type Course struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Currency    *string             `json:"currency,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Price       *float32            `json:"price,omitempty"`
	Status      *CourseStatus       `json:"status,omitempty"`

	// Subject Subject area, e.g. "english", "programming", "physics"
	Subject   *string             `json:"subject,omitempty"`
	TeacherId *openapi_types.UUID `json:"teacher_id,omitempty"`
	Title     *string             `json:"title,omitempty"`
	UpdatedAt *time.Time          `json:"updated_at,omitempty"`
}

// CourseStatus defines model for Course.Status.
type CourseStatus string

// CourseInput defines model for CourseInput.
type CourseInput struct {
	// Currency Defaults to "USD" when omitted.
	Currency    *string  `json:"currency,omitempty"`
	Description *string  `json:"description,omitempty"`
	Price       *float32 `json:"price,omitempty"`

	// Subject Defaults to "general" when omitted.
	Subject *string `json:"subject,omitempty"`
	Title   string  `json:"title"`
}

// CourseResult defines model for CourseResult.
type CourseResult struct {
	CourseId         *string `json:"course_id,omitempty"`
	DaysInactive     *int    `json:"days_inactive,omitempty"`
	LessonsCompleted *int    `json:"lessons_completed,omitempty"`
	LessonsTotal     *int    `json:"lessons_total,omitempty"`

	// ProgressPercent lessons_completed / lessons_total as a 0–100 value.
	ProgressPercent *float32            `json:"progress_percent,omitempty"`
	Status          *CourseResultStatus `json:"status,omitempty"`
	Title           *string             `json:"title,omitempty"`
}

// CourseResultStatus defines model for CourseResult.Status.
type CourseResultStatus string

// Lesson defines model for Lesson.
type Lesson struct {
	CourseId  *openapi_types.UUID `json:"course_id,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Position 1-based display order within the course
	Position  *int        `json:"position,omitempty"`
	Title     *string     `json:"title,omitempty"`
	Type      *LessonType `json:"type,omitempty"`
	UpdatedAt *time.Time  `json:"updated_at,omitempty"`
}

// LessonType defines model for Lesson.Type.
type LessonType string

// LessonData defines model for LessonData.
type LessonData struct {
	// ContentUrl Primary playable media URL for the lesson ("" when the lesson has no media).
	ContentUrl *string `json:"content_url,omitempty"`
	CourseId   *string `json:"course_id,omitempty"`

	// DurationSeconds Length of the primary media in seconds (0 when unknown).
	DurationSeconds *int `json:"duration_seconds,omitempty"`

	// LastProgressSeconds The learner's last saved playback offset (0 if never started).
	LastProgressSeconds *int                  `json:"last_progress_seconds,omitempty"`
	LessonId            *string               `json:"lesson_id,omitempty"`
	LessonType          *LessonDataLessonType `json:"lesson_type,omitempty"`
	Materials           *[]Material           `json:"materials,omitempty"`

	// MediaType Type of the primary media asset. Omitted when the lesson has no media.
	MediaType *LessonDataMediaType `json:"media_type,omitempty"`

	// PercentComplete The learner's saved completion percentage (0–100).
	PercentComplete *float32 `json:"percent_complete,omitempty"`
	Position        *int     `json:"position,omitempty"`
	Title           *string  `json:"title,omitempty"`
}

// LessonDataLessonType defines model for LessonData.LessonType.
type LessonDataLessonType string

// LessonDataMediaType Type of the primary media asset. Omitted when the lesson has no media.
type LessonDataMediaType string

// LessonInput defines model for LessonInput.
type LessonInput struct {
	LessonType LessonInputLessonType `json:"lesson_type"`
	Title      string                `json:"title"`
}

// LessonInputLessonType defines model for LessonInput.LessonType.
type LessonInputLessonType string

// Material defines model for Material.
type Material struct {
	// Id Present so the owning teacher's editor can reference this material (e.g. to delete it).
	Id    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Type  *string `json:"type,omitempty"`
	Url   *string `json:"url,omitempty"`
}

// Progress defines model for Progress.
type Progress struct {
	Completed       *bool      `json:"completed,omitempty"`
	LessonId        *string    `json:"lesson_id,omitempty"`
	PercentComplete *float32   `json:"percent_complete,omitempty"`
	ProgressSeconds *int       `json:"progress_seconds,omitempty"`
	UpdatedAt       *time.Time `json:"updated_at,omitempty"`
}

// StudentResults defines model for StudentResults.
type StudentResults struct {
	Courses *[]CourseResult `json:"courses,omitempty"`

	// CoursesCompleted Number of enrolled courses that are 100% complete.
	CoursesCompleted *int `json:"courses_completed,omitempty"`
	CoursesEnrolled  *int `json:"courses_enrolled,omitempty"`

	// OverallProgressPercent Completed lessons over total lessons across all enrolled courses (0–100).
	OverallProgressPercent *float32 `json:"overall_progress_percent,omitempty"`
}

// TeacherLesson defines model for TeacherLesson.
type TeacherLesson struct {
	CourseId   *string                  `json:"course_id,omitempty"`
	LessonId   *string                  `json:"lesson_id,omitempty"`
	LessonType *TeacherLessonLessonType `json:"lesson_type,omitempty"`
	Position   *int                     `json:"position,omitempty"`
	Title      *string                  `json:"title,omitempty"`
}

// TeacherLessonLessonType defines model for TeacherLesson.LessonType.
type TeacherLessonLessonType string

// TeacherMaterial defines model for TeacherMaterial.
type TeacherMaterial struct {
	Id    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Type  *string `json:"type,omitempty"`
	Url   *string `json:"url,omitempty"`
}

// TeacherMedia defines model for TeacherMedia.
type TeacherMedia struct {
	DurationSeconds *int                   `json:"duration_seconds,omitempty"`
	Id              *string                `json:"id,omitempty"`
	MediaType       *TeacherMediaMediaType `json:"media_type,omitempty"`
	Url             *string                `json:"url,omitempty"`
}

// TeacherMediaMediaType defines model for TeacherMedia.MediaType.
type TeacherMediaMediaType string

// TeacherProfile defines model for TeacherProfile.
type TeacherProfile struct {
	FullName *string             `json:"full_name,omitempty"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	Role     *TeacherProfileRole `json:"role,omitempty"`
}

// TeacherProfileRole defines model for TeacherProfile.Role.
type TeacherProfileRole string

// User defines model for User.
type User struct {
	// AvatarUrl Server-relative path to the profile picture, e.g. /uploads/avatars/{id}.jpg. Omitted when no avatar has been set.
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// Balance Virtual wallet balance (sandbox only)
	Balance  *float32             `json:"balance,omitempty"`
	Email    *openapi_types.Email `json:"email,omitempty"`
	FullName *string              `json:"full_name,omitempty"`
	Id       *openapi_types.UUID  `json:"id,omitempty"`
	Role     *UserRole            `json:"role,omitempty"`
}

// UserRole defines model for User.Role.
type UserRole string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetAnalyticsStudentMe200JSONResponseBodyCoursesStatus defines parameters for GetAnalyticsStudentMe.
type GetAnalyticsStudentMe200JSONResponseBodyCoursesStatus string

// GetAnalyticsTeacherDashboardParams defines parameters for GetAnalyticsTeacherDashboard.
type GetAnalyticsTeacherDashboardParams struct {
	CourseId string `form:"course_id" json:"course_id"`
}

// GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus defines parameters for GetAnalyticsTeacherDashboard.
type GetAnalyticsTeacherDashboard200JSONResponseBodyStudentsStatus string

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PostAuthRegisterJSONBody defines parameters for PostAuthRegister.
type PostAuthRegisterJSONBody struct {
	// AnonymousId Links pre-auth anonymous activity to this account, if any.
	AnonymousId *openapi_types.UUID          `json:"anonymous_id,omitempty"`
	Email       openapi_types.Email          `json:"email"`
	FullName    string                       `json:"full_name"`
	Password    string                       `json:"password"`
	Role        PostAuthRegisterJSONBodyRole `json:"role"`
}

// PostAuthRegisterJSONBodyRole defines parameters for PostAuthRegister.
type PostAuthRegisterJSONBodyRole string

// GetCatalogCoursesParams defines parameters for GetCatalogCourses.
type GetCatalogCoursesParams struct {
	// Search Course title/description keyword search
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Subject Partial, case-insensitive match against the course subject (e.g. "program" matches "Programming")
	Subject *string `form:"subject,omitempty" json:"subject,omitempty"`

	// MinPrice Lower bound (inclusive) for course price
	MinPrice *float32 `form:"min_price,omitempty" json:"min_price,omitempty"`

	// MaxPrice Upper bound (inclusive) for course price
	MaxPrice  *float32                          `form:"max_price,omitempty" json:"max_price,omitempty"`
	SortBy    *GetCatalogCoursesParamsSortBy    `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	SortOrder *GetCatalogCoursesParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`
	Page      *int                              `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *int                              `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetCatalogCoursesParamsSortBy defines parameters for GetCatalogCourses.
type GetCatalogCoursesParamsSortBy string

// GetCatalogCoursesParamsSortOrder defines parameters for GetCatalogCourses.
type GetCatalogCoursesParamsSortOrder string

// PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody defines parameters for PostPlayerCoursesCourseIdLessonsLessonIdProgress.
type PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody struct {
	// Completed Marks the lesson finished (forces percent_complete to 100).
	Completed *bool `json:"completed,omitempty"`

	// ProgressSeconds Current playback offset, in seconds.
	ProgressSeconds int `json:"progress_seconds"`
}

// PostPurchaseCheckoutJSONBody defines parameters for PostPurchaseCheckout.
type PostPurchaseCheckoutJSONBody struct {
	CourseId string `json:"course_id"`
}

// PostPurchaseRefundJSONBody defines parameters for PostPurchaseRefund.
type PostPurchaseRefundJSONBody struct {
	CourseId string `json:"course_id"`
}

// PostPurchaseWebhookJSONBody defines parameters for PostPurchaseWebhook.
type PostPurchaseWebhookJSONBody struct {
	CourseId      string                            `json:"course_id"`
	Status        PostPurchaseWebhookJSONBodyStatus `json:"status"`
	TransactionId string                            `json:"transaction_id"`
	UserId        string                            `json:"user_id"`
}

// PostPurchaseWebhookJSONBodyStatus defines parameters for PostPurchaseWebhook.
type PostPurchaseWebhookJSONBodyStatus string

// PatchTeacherCoursesCourseIdJSONBody defines parameters for PatchTeacherCoursesCourseId.
type PatchTeacherCoursesCourseIdJSONBody struct {
	// Currency Defaults to "USD" when omitted.
	Currency    *string                                   `json:"currency,omitempty"`
	Description *string                                   `json:"description,omitempty"`
	Price       *float32                                  `json:"price,omitempty"`
	Status      PatchTeacherCoursesCourseIdJSONBodyStatus `json:"status"`

	// Subject Defaults to "general" when omitted.
	Subject *string `json:"subject,omitempty"`
	Title   string  `json:"title"`
}

// PatchTeacherCoursesCourseIdJSONBodyStatus defines parameters for PatchTeacherCoursesCourseId.
type PatchTeacherCoursesCourseIdJSONBodyStatus string

// PutTeacherCoursesCourseIdLessonsOrderJSONBody defines parameters for PutTeacherCoursesCourseIdLessonsOrder.
type PutTeacherCoursesCourseIdLessonsOrderJSONBody struct {
	// LessonIds Every lesson id in the course, in the desired order.
	LessonIds []string `json:"lesson_ids"`
}

// PostTeacherCoursesCourseIdLessonsLessonIdMaterialsJSONBody defines parameters for PostTeacherCoursesCourseIdLessonsLessonIdMaterials.
type PostTeacherCoursesCourseIdLessonsLessonIdMaterialsJSONBody struct {
	Title string `json:"title"`

	// Type Free-form attachment kind, e.g. "pdf", "zip", "link".
	Type *string `json:"type,omitempty"`
	Url  string  `json:"url"`
}

// PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBody defines parameters for PutTeacherCoursesCourseIdLessonsLessonIdMedia.
type PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBody struct {
	DurationSeconds *int                                                           `json:"duration_seconds,omitempty"`
	MediaType       PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBodyMediaType `json:"media_type"`
	Url             string                                                         `json:"url"`
}

// PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBodyMediaType defines parameters for PutTeacherCoursesCourseIdLessonsLessonIdMedia.
type PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBodyMediaType string

// PostUsersMeAvatarMultipartBody defines parameters for PostUsersMeAvatar.
type PostUsersMeAvatarMultipartBody struct {
	Avatar openapi_types.File `json:"avatar"`
}

// PatchUsersMeEmailJSONBody defines parameters for PatchUsersMeEmail.
type PatchUsersMeEmailJSONBody struct {
	CurrentPassword string              `json:"current_password"`
	NewEmail        openapi_types.Email `json:"new_email"`
}

// PatchUsersMeNameJSONBody defines parameters for PatchUsersMeName.
type PatchUsersMeNameJSONBody struct {
	FullName string `json:"full_name"`
}

// PatchUsersMePasswordJSONBody defines parameters for PatchUsersMePassword.
type PatchUsersMePasswordJSONBody struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody PostAuthRegisterJSONBody

// PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONRequestBody defines body for PostPlayerCoursesCourseIdLessonsLessonIdProgress for application/json ContentType.
type PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONRequestBody PostPlayerCoursesCourseIdLessonsLessonIdProgressJSONBody

// PostPurchaseCheckoutJSONRequestBody defines body for PostPurchaseCheckout for application/json ContentType.
type PostPurchaseCheckoutJSONRequestBody PostPurchaseCheckoutJSONBody

// PostPurchaseRefundJSONRequestBody defines body for PostPurchaseRefund for application/json ContentType.
type PostPurchaseRefundJSONRequestBody PostPurchaseRefundJSONBody

// PostPurchaseWebhookJSONRequestBody defines body for PostPurchaseWebhook for application/json ContentType.
type PostPurchaseWebhookJSONRequestBody PostPurchaseWebhookJSONBody

// PostTeacherCoursesJSONRequestBody defines body for PostTeacherCourses for application/json ContentType.
type PostTeacherCoursesJSONRequestBody = CourseInput

// PatchTeacherCoursesCourseIdJSONRequestBody defines body for PatchTeacherCoursesCourseId for application/json ContentType.
type PatchTeacherCoursesCourseIdJSONRequestBody PatchTeacherCoursesCourseIdJSONBody

// PostTeacherCoursesCourseIdLessonsJSONRequestBody defines body for PostTeacherCoursesCourseIdLessons for application/json ContentType.
type PostTeacherCoursesCourseIdLessonsJSONRequestBody = LessonInput

// PutTeacherCoursesCourseIdLessonsOrderJSONRequestBody defines body for PutTeacherCoursesCourseIdLessonsOrder for application/json ContentType.
type PutTeacherCoursesCourseIdLessonsOrderJSONRequestBody PutTeacherCoursesCourseIdLessonsOrderJSONBody

// PatchTeacherCoursesCourseIdLessonsLessonIdJSONRequestBody defines body for PatchTeacherCoursesCourseIdLessonsLessonId for application/json ContentType.
type PatchTeacherCoursesCourseIdLessonsLessonIdJSONRequestBody = LessonInput

// PostTeacherCoursesCourseIdLessonsLessonIdMaterialsJSONRequestBody defines body for PostTeacherCoursesCourseIdLessonsLessonIdMaterials for application/json ContentType.
type PostTeacherCoursesCourseIdLessonsLessonIdMaterialsJSONRequestBody PostTeacherCoursesCourseIdLessonsLessonIdMaterialsJSONBody

// PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONRequestBody defines body for PutTeacherCoursesCourseIdLessonsLessonIdMedia for application/json ContentType.
type PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONRequestBody PutTeacherCoursesCourseIdLessonsLessonIdMediaJSONBody

// PostUsersMeAvatarMultipartRequestBody defines body for PostUsersMeAvatar for multipart/form-data ContentType.
type PostUsersMeAvatarMultipartRequestBody PostUsersMeAvatarMultipartBody

// PatchUsersMeEmailJSONRequestBody defines body for PatchUsersMeEmail for application/json ContentType.
type PatchUsersMeEmailJSONRequestBody PatchUsersMeEmailJSONBody

// PatchUsersMeNameJSONRequestBody defines body for PatchUsersMeName for application/json ContentType.
type PatchUsersMeNameJSONRequestBody PatchUsersMeNameJSONBody

// PatchUsersMePasswordJSONRequestBody defines body for PatchUsersMePassword for application/json ContentType.
type PatchUsersMePasswordJSONRequestBody PatchUsersMePasswordJSONBody
